# Generated by Django 5.2.8 on 2025-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='provider',
            field=models.CharField(choices=[('dummy', 'Dummybot'), ('openai', 'OPEN AI based Bot'), ('openai_rag', 'OPEN AI RAG based Bot')], default='dummy', max_length=30),
        ),
    ]
