### Continue Chat (Session 3)
POST http://localhost:8000/api/chat/session/1/chat
Content-Type: application/json
Authorization: Token ee1764d4c1b32d8cf7cccfc1b14022e4ba429e72

{
  "prompt": "Gibt es was erwähnenswertes in der Rudolf Weber Arena"
}