### POST Event anlegen (category-list-create)
POST http://127.0.0.1:8000/api/events/
Content-Type: application/json
Authorization: Token ee1764d4c1b32d8cf7cccfc1b14022e4ba429e72

{
    "name": "Event API Test 1",
    "sub_title": "sdfasdf",
    "date": "2029-04-20T10:00:00Z",
    "min_group": 5,
    "category": 2
}


### GET Events auflisten
GET http://127.0.0.1:8000/api/events/



### POST Event anlegen mit proxy header(category-list-create)
POST http://127.0.0.1:8000/api/events/
Content-Type: application/json
X-Auth-Request-User: Peter
X-Auth-Request-Email: peter@example.com

{
    "name": "Event API Test 1",
    "sub_title": "Api Subtitle",
    "date": "2029-04-20T10:00:00Z",
    "min_group": 5,
    "category": 2
}
