# Generated by Django 5.2.8 on 2025-11-10 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_options_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='min_group',
            field=models.IntegerField(choices=[(10, 'mittelgroße Gruppe'), (2, 'sehr kleine Gruppe'), (5, 'mittelgroße Gruppe'), (20, 'sehr große Gruppe'), (0, 'kein Limit')], default=0),
            preserve_default=False,
        ),
    ]
